#Tue Feb 07 01:12:37 CET 2024
android.builtInKotlin=true
android.dependency.useConstraints=true
android.newDsl=false
android.r8.optimizedResourceShrinking=false
android.r8.strictFullModeForKeepRules=false
android.uniquePackageNames=false
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false
android.useAndroidX=true
org.gradle.jvmargs=-Xmx4g
ksp.incremental=false
ksp.incremental.intermodule=false
TOPON_APP_ID=h69d4ba03a9a66
TOPON_APP_KEY=af8b0ffad212b6f57ca6e6a317e4b34ee
