# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx4608m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
android.useAndroidX=true
android.enableJetifier=true
android.apk.enableUncompressedNativeLibs=false
android.nonTransitiveRClass=false
android.nonFinalResIds=false
ABI_FILTERS=armeabi-v7a;arm64-v8a;x86;x86_64
ksp.incremental=false
ksp.incremental.intermodule=false
APP_PACKAGE_NAME=com.myAllVideoBrowser
ADMOB_APP_ID=
TOPON_TEST_MODE=true
TOPON_APP_ID=h69d4ba03a9a66
TOPON_APP_KEY=af8b0ffad212b6f57ca6e6a317e4b34ee
TEST_TOPON_APP_ID=h69e0d96c8e3af
TEST_TOPON_APP_KEY=a46c81dc0bb003d814103dc5b7abbd70a
TEST_TOPON_SPLASH_PLACEMENT_ID=n1h9mmu52muv52
TEST_TOPON_INTERSTITIAL_PLACEMENT_ID=n1h9mmu52mv3d3
TEST_TOPON_REWARDED_PLACEMENT_ID=
TEST_TOPON_BANNER_PLACEMENT_ID=
TEST_TOPON_NATIVE_PLACEMENT_ID=n1h9mmu52n0afu
TEST_TOPON_APP_PACKAGE_NAME=com.test.topon.app
TEST_ADMOB_APP_ID=ca-app-pub-3940256099942544~3347511713
